# Prometheus instant — retention 2d. Краткосрочные метрики (node_exporter и т.п.)

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: localhost_node_exporter
    static_configs:
      - targets: ["host.docker.internal:9100"]
